filter:
    excluded_paths: [vendor/*, tests/*, .tx/*, includes/libraries/*, bin/*, assets/*, templates/* ]

tools:
    php_code_sniffer:
        config:
            # https://scrutinizer-ci.com/docs/tools/php/code-sniffer/standards
            standard: WordPress

tools:

    php_mess_detector:
        config:
            code_size_rules:
                cyclomatic_complexity:  false
                npath_complexity:     false
                excessive_method_length:  false
                excessive_class_length:  false
                excessive_parameter_list:  false
                excessive_public_count:  false
                too_many_fields:      false
                too_many_methods:     false
                excessive_class_complexity:  false

    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
