language: php

sudo: false

php:
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0

matrix:
    allow_failures:
     - env: WP_VERSION=bleeding WP_MULTISITE=0
     - env: WP_VERSION=bleeding-maintenance WP_MULTISITE=0

    include:
    # MySQL 5.7
    #- env: DB=mysql-5.7-dmr WP_VERSION=latest WP_MULTISITE=0

## Cache composer bits
cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.composer/cache

before_script:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
    - composer self-update
    - composer install --no-interaction --prefer-source
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - ln -s . /tmp/wordpress/wp-content/plugins/pods
    - npm install

script:
    # - vendor/bin/phpunit
    node --harmony ./node_modules/mocha/bin/_mocha --compilers js:babel-core/register --ui bdd --recursive tests-js

branches:
    only:
        - feature/#3639_JS_unit_tests
