language: php

sudo: false

php:
    - 5.3
    - 5.6

env:
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=1
    - WP_VERSION=4.3 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

matrix:
    allow_failures:
     - php: hhvm
     - php: 7.0
     - env: WP_VERSION=nightly WP_MULTISITE=0
     - env: WP_VERSION=nightly WP_MULTISITE=1

    include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=latest WP_MULTISITE=0

## Cache composer bits
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - ln -s . /tmp/wordpress/wp-content/plugins/pods

script:
    - vendor/bin/phpunit

branches:
    only:
        - master
        - 2.x
        - release/3.0
