language: php

sudo: false

php:
    - 7.1

env:
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

matrix:
    allow_failures:
     - env: WP_VERSION=nightly WP_MULTISITE=0

    include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
      env: NODE_RELEASE=stable
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0
      env: NODE_RELEASE=stable
    - php: 5.3
      env: WP_VERSION=4.5 WP_MULTISITE=0
      dist: precise
      env: NODE_RELEASE=7

    # MySQL 5.7
    #- env: DB=mysql-5.7 WP_VERSION=latest WP_MULTISITE=0
    # MySQL 8.0
    #- env: DB=mysql-8.0-dmr WP_VERSION=latest WP_MULTISITE=0

## Cache composer and node bits
cache:
    apt: true
    directories:
        - vendor
        - node_modules
        - $HOME/.composer/cache

before_install:
    - . $HOME/.nvm/nvm.sh
    - nvm install ${NODE_RELEASE}
    - nvm use ${NODE_RELEASE}
    - npm install

before_script:
    - bash bin/init.sh
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - ln -s . /tmp/wordpress/wp-content/plugins/pods

script:
    - vendor/bin/phpunit
    - npm run test-dfv
